import { Bookmark, ChatRound, Programming } from "@solar-icons/react";

// ─── Schedule ─────────────────────────────────────────────────────────────────

export const DAYS = [
  { label: "T2", value: 1 },
  { label: "T3", value: 2 },
  { label: "T4", value: 3 },
  { label: "T5", value: 4 },
  { label: "T6", value: 5 },
  { label: "T7", value: 6 },
  { label: "CN", value: 0 },
] as const;

export const HOURS = Array.from({ length: 24 }, (_, i) => i);

export interface ScheduleState {
  days: number[];
  fromHour: number;
  toHour: number;
  intervalMinutes: number;
  startMessage: string;
}

export const DEFAULT_SCHEDULE: ScheduleState = {
  days: [],
  fromHour: 9,
  toHour: 18,
  intervalMinutes: 30,
  startMessage: "",
};

export function buildCron(s: ScheduleState): string {
  if (s.days.length === 0) return "";
  const dow = s.days
    .slice()
    .sort((a, b) => a - b)
    .join(",");
  if (s.intervalMinutes < 60) return `*/${s.intervalMinutes} ${s.fromHour}-${s.toHour} * * ${dow}`;
  const hi = s.intervalMinutes / 60;
  return hi === 1 ? `0 ${s.fromHour}-${s.toHour} * * ${dow}` : `0 ${s.fromHour}-${s.toHour}/${hi} * * ${dow}`;
}

/**
 * Parse a cron expression back into a ScheduleState.
 * Supports the formats generated by `buildCron`.
 */
export function parseCron(cron: string | null | undefined): ScheduleState {
  if (!cron?.trim()) return { ...DEFAULT_SCHEDULE };

  const parts = cron.trim().split(/\s+/);
  if (parts.length < 5) return { ...DEFAULT_SCHEDULE };

  const [minute, hour, , , dow] = parts;

  // Parse days
  const days = dow
    .split(",")
    .map(Number)
    .filter((n) => !Number.isNaN(n));

  // Parse hour range (e.g. "9-18" or "9-18/2")
  let fromHour = 9;
  let toHour = 18;
  const hourMatch = hour.match(/^(\d+)-(\d+)(?:\/(\d+))?$/);
  if (hourMatch) {
    fromHour = Number(hourMatch[1]);
    toHour = Number(hourMatch[2]);
  }

  // Parse interval
  let intervalMinutes = 30;
  const minuteStepMatch = minute.match(/^\*\/(\d+)$/);
  if (minuteStepMatch) {
    intervalMinutes = Number(minuteStepMatch[1]);
  } else if (minute === "0") {
    // Hourly or multi-hour
    const hourStep = hourMatch?.[3];
    intervalMinutes = hourStep ? Number(hourStep) * 60 : 60;
  }

  return { days, fromHour, toHour, intervalMinutes, startMessage: "" };
}

// ─── Tab definitions ──────────────────────────────────────────────────────────

export type TabId = "chat" | "memory" | "editor";
export const TABS: { id: TabId; label: string; icon: typeof ChatRound; desc: string; path: string }[] = [
  {
    id: "chat",
    label: "Chat",
    icon: ChatRound,
    desc: "Chat with the agent",
    path: "",
  },
  {
    id: "memory",
    label: "Memory",
    icon: Bookmark,
    desc: "User knowledge graph",
    path: "memory",
  },
  {
    id: "editor",
    label: "Editor",
    icon: Programming,
    desc: "Agent flow editor",
    path: "editor",
  },
];

// ─── Animation variants ───────────────────────────────────────────────────────

export const tabVariants = {
  enter: { opacity: 0, y: 10 },
  center: { opacity: 1, y: 0 },
  exit: { opacity: 0, y: -6 },
};
